tap "drone/drone"
tap "fluxcd/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# brew "python@3.9"
# brew "autossh"
# brew "coreutils"
# brew "ctags"
brew "curl"
# brew "ddrescue"
# brew "emacs"
brew "fluxcd/tap/flux"
# brew "freeciv"
# brew "ghostscript"
brew "git"
# brew "graphicsmagick"
# brew "graphviz"
# brew "helm"
# brew "htop"
# brew "httperf"
# brew "httpie"
brew "hub"
brew "hugo"
# brew "imagemagick"
brew "istioctl"
# brew "oniguruma"
brew "jq"
brew "k3d"
brew "kompose"
brew "kustomize"
brew "mas"
brew "mkcert"
brew "nvm"
# brew "postgresql"
# brew "pg_top"
# brew "ruby"
# brew "scrcpy"
# brew "siege"
brew "sops"
# brew "sshuttle"
# brew "telnet"
# brew "tmux"
# brew "tsung"
# brew "unrar"
brew "watch"
brew "wget"
brew "yq"
cask "android-platform-tools"
cask "docker"
cask "dropbox"
cask "flux"
cask "fork"
# cask "gitx"
cask "google-chrome"
cask "iterm2"
cask "lens"
# cask "licecap"
# cask "webpquicklook"
cask "visual-studio-code"
cask "zoom"
mas "1Password 7 - Password Manager", id: 1333542190
mas "Evernote", id: 406056744
mas "Xcode", id: 497799835